### ISSUE TITLE
Add save button

### ISSUE THREAD

**Issue by axel-kaliff** [inda19plusplus/logik#23]
Button in GUI (duh) that saves data to XML file

**Comment by violaso** [comment]
### Tasks
- Add `MenuItem` named "Save..."
- Add `MenuItem` named "Save as..."
- Add write functionality to `FileManager`
- Access violation bug caused by [`Dialog.Run()`](http://docs.go-mono.com/?link=M%3aGtk.Dialog.Run()) must be solved!
- Discuss global project parameters, like project name and version.

**Comment by NogginBops** [comment]
Technically this is in.
